name: pushToFeature

on:
  push:
    branches:
      - Actions

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install Salesforce CLI
        uses: sfdx-actions/setup-sfdx@v3
        with:
          sfdx-version: 'latest'

      - name: Authorize target org
        run: |
          echo "${{ secrets.TARGET_ORG_JWT }}" | base64 -d > jwt.key
          sfdx force:auth:jwt:grant --clientid "${{ secrets.TARGET_ORG_CONSUMER_KEY }}" --jwtkeyfile jwt.key --username "${{ secrets.TARGET_ORG_USERNAME }}" --setdefaultdevhubusername -a target

      - name: Deploy source code
        env:
          SFDX_DEFAULTUSERNAME: ${{ secrets.TARGET_ORG_USERNAME }}
        run: sfdx force:source:deploy --sourcepath force-app --json
