name: PushToFeature
on:
  push:
      branches: actions
jobs:
  action-pull-request:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Run the Action
      if: startsWith(github.ref, 'refs/heads/demo'
      uses: devops-infra/action-pull-request@v0.4.2
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_SCOPED_TOKEN }}
      with:
        github_token: ${{ secrets.REPO_SCOPED_TOKEN }}
        title: Automatic pull request
        get_diff: true
  
