name: Deploy to Dev Org
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
      - name: Install SFDX CLI
        run: |
          wget -qO- https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz | tar xJf -
          ./sfdx/install
      - name: Authenticate to Dev Org
        env:
          SFDX_LOGIN_URL: ${{ secrets.SFDX_LOGIN_URL }}
          SFDX_USERNAME: ${{ secrets.SFDX_USERNAME }}
          SFDX_DEVHUB_USERNAME: ${{ secrets.SFDX_DEVHUB_USERNAME }}
        run: |
          echo "Setting up Dev Hub..."
          sfdx force:auth:sfdxurl:store -f $SFDX_LOGIN_URL -d -a $SFDX_DEVHUB_USERNAME
          echo "Setting up Dev Org..."
          sfdx force:auth:sfdxurl:store -f $SFDX_LOGIN_URL -a $SFDX_USERNAME
          echo "Creating scratch org..."
          sfdx force:org:create -f config/project-scratch-def.json -s -a scratch-org
      - name: Deploy to Dev Org
        env:
          SFDX_USERNAME: ${{ secrets.SFDX_USERNAME }}
        run: |
          echo "Deploying to Dev Org..."
          sfdx force:source:deploy -u $SFDX_USERNAME -p force-app/main/default/
      - name: Run Apex Tests
        env:
          SFDX_USERNAME: ${{ secrets.SFDX_USERNAME }}
        run: |
          echo "Running Apex tests..."
          sfdx force:apex:test:run -u $SFDX_USERNAME -w 5 -c -r human
      - name: Delete Scratch Org
        env:
          SFDX_DEVHUB_USERNAME: ${{ secrets.SFDX_DEVHUB_USERNAME }}
        run: |
          echo "Deleting scratch org..."
          sfdx force:org:delete -u scratch-org -p -v $SFDX_DEVHUB_USERNAME
