name: push
on:
  push:
    branches:
      - Actions
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install Salesforce CLI
        uses: varsha-fexle/Demo@v2.3
      - name: Authenticate with Salesforce Org
        run: sfdx force:auth:jwt:grant --clientid ${{ secrets.TARGET_ORG_CONSUMER_KEY }} --jwtkeyfile server.key --username ${{ secrets.TARGET_ORG_USERNAME }} --setdefaultdevhubusername --setdefaultusername
      - name: Deploy to Salesforce Org
        run: sfdx force:source:deploy -p force-app/main/default -w 5
